language: node_js
node_js:
- 8
install: true
addons:
  sauce_connect: true
jobs:
  include:
  - stage: test
    script:
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash .travis/run_on_pull_requests.sh;
      fi
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash .travis/run_on_non_pull_requests.sh;
      fi
    after_success:
    - bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: ljxoSUkCW24qqKGhNuXciaKgrGn6pWMng7HAWCwpiMIHc5MeEtkgU/3HwkzRmlSnptCz6YNhf2w61dTT/NluCVZo3zyjf06iVmY3I8tEm75jl+IBfj3xk9oE54vIMjyPmiGR3yZMdVRlvKFAQyPtsEvZK++4/WJHZJZ8ItYnvTa+3QqzofjLAXjAxj2Ch4Q+jqD3BMzaaK/ZJi5w8pMNHczjtyxreImBK38ElOLlBxeYP2HCe41XXWjA5sgGrn6kJwUvYsAlyp2rTviNnvsnKYOePQuTjnlLchgWgtyfYhhuVhNfm75hBCDN4IE6gRcP5p22B9r2cuCVfYdjhwrsBlG9FtRPZjyzUkYc/vTLdBnJKPVuqkVRmcok/daPMxs5d2kiXeZwttr6cHBljlRQQG8ulApO05KCJGaTX4DNyY1C+Z1b4ncuHcS2lCw2Do9CbnRiWGFVu2aFZ7lzvaAhX1VVULULX20ymQqkHtKOBZq1rDn+UsZf0MFKtTICkgjn5XqOBVULXkjOvcnTCyKY2znPuvVtIq+bqFVk3Z6U9E0Lb8/ussotYEfwE3NyEVgimIaiNiiRI/0F/u8Xdv2LAql8tfROzVP6IWKRlLeZliH3RRtGMVckQU+AIEshXBCko5DqiXERqCYQNMlWJnBWetXlszNqRCssNrrI89P3xQk=
